- src/hooks/useSigninData.tsx
add ABI suffix to getPSPDetails
expected)
> add ABI suffix to getPSPDetails

- .github/workflows/release_deploy.yml
Restore previous feature flags values
With the migration from azure pipeline, some variables lost their values
Manually
expected)
> reset feature flags to previous az pipeline values

- src/api/PortalApiClient.ts
- src/pages/channels/list/ChannelsTable.tsx
add brokerCode filter to getAllChannels
bug fix
expected)
> PASELC-362 add brokerCode filter to getAllChannels

- src/locale/it.json
- src/pages/apiKeys/ApiKeysCard.tsx
- remove apikey displayName translation
- fix header env chip label
Apikeys from backend wasn't interpolated correctly.
Env label on header wasn't interpolated correctly.
manually
expected)
> Paselc 440

- src/services/__mocks__/ibanService.ts
Add labels to IbanResource
Labels are needed to render correct value in standin and cup form
expected)
> PASELC-396 add labels on IbanResource

- src/locale/it.json
- src/pages/stations/__tests__/AddEditStationForm.test.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- src/pages/stations/detail/components/StationDetailsValidation.tsx
Remove "Redirect" section from station creation and edit form.
Remove "Redirect" section from station detail
CR
Manually and via Jest
expected)
> PASELC-425 remove redirect from station form and detail

- src/locale/it.json
- src/model/Station.tsx
- src/pages/stations/__tests__/AddEditStationForm.test.tsx
- src/pages/stations/__tests__/StationDetails.test.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- src/pages/stations/detail/components/StationDetailsValidation.tsx
Add endpoint field
Add endpoint url validation
CR
Manually and via JEST
expected)
> PASELC-427 add endpoint to Stations

- src/locale/it.json
- src/model/Station.tsx
- src/pages/stations/__tests__/AddEditStationForm.test.tsx
- src/pages/stations/__tests__/StationDetailsValidation.test.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/addEditStation/components/AddEditStationFormValidation.tsx
- src/pages/stations/detail/components/StationDetailsValidation.tsx
Add proxy to Station form and to station detail page
CR
Manually and via JEST
expected)
> PASELC-431 add proxy to station form and detail

- src/components/CommonHeader/CommonHeader.tsx
Clear user and token from the localStorage on user logout
bugfix
manually
expected)
> PASELC-335 clear storage user and token on logout

- src/model/Station.tsx
- src/pages/stations/__tests__/AddEditStationForm.test.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- src/pages/stations/detail/components/StationDetailsValidation.tsx
- src/utils/__tests__/station-utils.test.ts
- src/utils/station-utils.ts
update env names
bug fix
manually and via jest
expected)
> fix env name for station configs

- openApi/portal-api-docs.json
- src/api/PortalApiClient.ts
- src/model/Channel.tsx
- src/pages/channels/addEditChannel/AddEditChannelForm.tsx
- src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
- src/pages/channels/addEditChannel/components/AddEditChannelValidationForm.tsx
- src/pages/channels/detail/components/ChannelDetails.tsx
> made some fix for channel creation/validation

- src/locale/it.json
- src/pages/iban/addEditIban/AddEditIbanForm.tsx
> disambiguate postal Iban already created from duplicate iban

- src/locale/it.json
- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
> Fix-iban-datePicker

- src/locale/it.json
- src/pages/channels/addEditChannel/AddEditChannelForm.tsx
- src/pages/channels/addEditChannel/AddEditChannelPage.tsx
- src/pages/channels/addEditChannel/__tests__/AddEditChannelPage.test.tsx
- src/pages/channels/addEditChannel/components/AddEditChannelValidationForm.tsx
- src/pages/iban/detail/IbanDetailPage.tsx
- src/pages/iban/detail/__tests__/IbanDetailPage.test.tsx
- src/pages/iban/list/IbanTableColumns.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/addEditStation/components/AddEditStationFormValidation.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- src/pages/stations/detail/components/StationDetailsValidation.tsx
> PASELC-482

- src/api/PortalApiClient.ts
- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- src/pages/iban/detail/IbanDetailPage.tsx
- src/pages/iban/list/IbanTableColumns.tsx
> fix iban dates controls

- src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
> PASELC-496

- src/api/PortalApiClient.ts
- src/pages/channels/addEditChannel/AddEditChannelForm.tsx
- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/detail/components/StationDetailsValidation.tsx
> PASELC-490/491/492/495

- src/pages/iban/addEditIban/AddEditIbanForm.tsx
> fixed creditorInstitutionCode on ecOwner radio buttons

- package.json
> restart version from 0.0.1

- .github/workflows/release_deploy.yml
- package.json
upgrade to pagopa/github-actions-template/node-release@v1.6.6 so pipeline can bump package.json version correctly
manually
expected)
> Fix pipeline make release version

- src/api/PortalApiClient.ts
Replace 204 with 201 as expected in openApi in create-psp-direct service
Expected response was wrong
manually
expected)
> fix expected response 201 on createPSPDirect

- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- switched getCreditorInstitutionSegregationcodes from the real one to the mocked one
expected)
> switched api call getCreditorInstitutionSegregationcodes to the mocked one

- openApi/portal-api-docs.json
- src/components/Header.tsx
- src/components/__tests__/Header.test.tsx
- src/locale/it.json
Add a function to remap user roles from Selfcare to the roles used in Pagamenti Pagopa. 
This function is used in the header component
Currently, the Header component displays incorrect role names.
manually
expected)
> add roles translation on header based on institution type

- src/pages/channels/addEditChannel/AddEditChannelForm.tsx
- fixed the calling position of the function splitNewConnection
expected)
> fixed call of the function splitNewConnection in pre-submit

- src/api/PortalApiClient.ts
- src/locale/it.json
- src/pages/stations/stationAssociateEC/ECAccountItemSelection.tsx
- src/pages/stations/stationAssociateEC/ECSelectionSearch.tsx
- src/pages/stations/stationAssociateEC/ECSelectionSearchItemContainer.tsx
- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- src/pages/stations/stationAssociateEC/__tests__/ECSelectionSearch.test.tsx
- finished integration with BE for services about association of EC to station
- fixed the selection of the available EC to the station
- fixed pointerEvents fot CustomBox of EcSelectionSearch component
- fixed test
expected)
> Paselc 334

- .env.development.local
- .github/workflows/release_deploy.yml
- src/App.tsx
- src/components/SideMenu/SideMenu.tsx
- src/locale/it.json
- src/pages/commisionalPackages/CommisionalPackagesPage.tsx
- src/pages/commisionalPackages/__tests__/CommisionalPackagesEmpty.test.tsx
- src/pages/commisionalPackages/__tests__/CommisionalPackagesPage.test.tsx
- src/pages/commisionalPackages/__tests__/TabPanels.test.tsx
- src/pages/commisionalPackages/components/CommisionalPackagesEmpty.tsx
- src/pages/commisionalPackages/components/TabPanels.tsx
- src/routes.tsx
- src/utils/env.ts
- created new routes for commisional packages
- added homepage for commisional packages
- added new menu option to SideMenu for commissional packages
- added test for new commisional packages components
- new components tested with testing-library/react
expected)
> Paselc 523

- src/pages/dashboard/components/NextSteps.tsx
- src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
- src/pages/iban/detail/IbanDetailPage.tsx
- src/pages/iban/detail/__tests__/IbanDetailButtons.test.tsx
- src/pages/iban/detail/__tests__/IbanDetailPage.test.tsx
- src/pages/iban/detail/components/IbanDetailButtons.tsx
- src/pages/iban/list/IbanTableColumns.tsx
- src/pages/iban/list/__tests__/IbanTable.test.tsx
- src/services/__mocks__/ibanService.ts
Remove status rendering from ibans table and iban detail page
Iban status cycle doesnt works as expected so we will treat the status as active by default
Manually and via jest
expected)
> PASELC-536 hide status from iban table and detail

- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- src/services/__mocks__/nodeService.ts
- fixed the import of api from the mocked one to the real one
expected)
> updated importo of getCreditorInstitutionSegregationcodes

- .env.development.local
- openApi/portal-api-docs.json
- sonar-project.properties
- src/api/PortalApiClient.ts
- src/hooks/useSigninData.tsx
- src/model/Node.tsx
- src/pages/dashboard/__tests__/PSPRegistrationData.test.tsx
- src/pages/dashboard/components/PSPRegistrationData.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPage.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
- src/services/__mocks__/nodeService.ts
- src/services/nodeService.ts
add getBrokerAndPspDetails
expected)
> Paselc 550 add getBrokerAndPspDetails

- src/api/PortalApiClient.ts
- src/locale/it.json
- src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInECForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
- src/pages/dashboard/nodeSignIn/components/CommonRadioGroup.tsx
- src/services/__mocks__/nodeService.ts
- src/services/nodeService.ts
- Added intermediation flag for psp/ec
- Updated the logic of api calls based on the psp/ec flag
- Updated tests
- Added tooltip for radiobutton
expected)
> Paselc 498

- src/api/PortalApiClient.ts
- src/api/__tests__/PortalApiClient.test.ts
- src/hooks/useSigninData.tsx
- src/model/Node.tsx
- src/pages/dashboard/components/ECRegistrationData.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPage.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInECForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
- src/services/__mocks__/nodeService.ts
- src/services/nodeService.ts
add getBrokerAndEcDetails to fetch EC and ECBroker details
expected)
> PASELC-549 add getBrokerAndEcDetails

- src/locale/it.json
- src/pages/commisionalPackages/__tests__/AddEditCommissionPackageForm.test.tsx
- src/pages/commisionalPackages/addEditCommissionPackage/components/AddEditCommissionPackageForm.tsx
- src/pages/dashboard/nodeSignIn/components/CommonRadioGroup.tsx
- switched tooltip from radiogroup of form node psp/ec 
- updated labels for radiogroup of form node psp/ec 
- changed decimal separator from . to for commission packages form
expected)
> fix for  NodeSignIn PSP/EC form  and AddEditCommissionPackageForm

- src/App.tsx
Enable add apikey form if dashboard is not visible
expected)
> fix add apikey permission if dashboard not enabled

- src/utils/rbac-utils.ts
- Added option of null on the controls of ec/psp signed on the node
expected)
> Fix - added option of null on controls of psp/ec signed on the node

- openApi/portal-api-docs.json
- src/locale/it.json
- src/model/Node.tsx
- src/pages/dashboard/DashboardPage.tsx
- src/pages/dashboard/__tests__/DashboardPage.test.tsx
- src/pages/dashboard/__tests__/PSPRegistrationData.test.tsx
- src/pages/dashboard/components/CommonDetails.tsx
- src/pages/dashboard/components/ECRegistrationData.tsx
- src/pages/dashboard/components/PSPRegistrationData.tsx
- src/pages/dashboard/components/PTRegistrationData.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPage.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPage.test.tsx
- Updated dashboard for PT and updated its test
- Added PTRegistrationData and its test
- Updated NodeSignInPage and its test
- Added NodeSignInPTForm and its test
- updated open-api
expected)
> Paselc 569

- integration-test/00_login_ec.js
- public/index.html
- src/components/Header.tsx
- src/model/__tests__/Product.test.ts
- Changed commercial denomination
expected)
> switched commercial denomination form "Pagamenti pagoPa" to "Piattaforma pagoPa"

- src/components/Header.tsx
Add environment param management to party switcher
When switching institution/party from backoffice app, users are redirected to the default environment.
By adding the environment parameter the user can be redirected to the desired env.
expected)
> PASELC-583 add environment mgmt for partySwitcher

- src/components/Header.tsx
> Paselc 583

- openApi/portal-api-docs.json
- src/api/PortalApiClient.ts
- src/hooks/useSigninData.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
- src/services/__mocks__/nodeService.ts
- src/services/nodeService.ts
- Updated open-api
- Updated client with 2 new services
- Updated service file with 2 new api-call
- Updated mocks
- Updated useSignInData to make sure that the get of psp details it's called with pspCode
expected)
> Added filter fiscal code for findByPspCode

- .github/workflows/release_deploy.yml
> Enable dashboards, channels, stations and operation-table in prod

- src/hooks/useSigninData.tsx
- Fixed error on psp_code updating pspDetails controls
expected)
> Fix useSignInData custom hook

- src/pages/channels/detail/components/ChannelDetailsWrap.tsx
- added ":" before the port on target EndPoint detail
expected)
> Fix Channel details

- src/components/SideMenu/SideMenu.tsx
- src/components/SideMenu/__tests__/SideMenu.test.tsx
- src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
- src/pages/channels/detail/ChannelDetailPage.tsx
- src/pages/channels/detail/components/ChannelDetails.tsx
- src/pages/channels/detail/components/ChannelDetailsWrap.tsx
- src/pages/dashboard/components/ECRegistrationData.tsx
- src/pages/stations/__tests__/StationDetailPage.test.tsx
- src/pages/stations/detail/StationDetailPage.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- src/services/__mocks__/nodeService.ts
- src/services/nodeService.ts
> PASELC-592 PASELC-591 + fix delegation param

- .github/workflows/release_deploy.yml
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
This PR contains a change on a feature flag for the BackOffice portal: this change permits to enable all the functionalities related to the IBANs in UAT environment. 
- Enabled the feature flag related to IBANs functionalities
This change is required in order to permits the testing of this functionalities for the pilot users.
expected)
> [PASELC-610] feat: enabled IBANs functionality

- openApi/portal-api-docs.json
- package.json
- src/model/Party.tsx
- src/model/PartyDetail.tsx
> [PASELC-623] fix: resolved optional fields

- package.json
- src/model/Iban.tsx
- src/pages/iban/IbanPage.tsx
- src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- src/pages/iban/addEditIban/AddEditIbanPage.tsx
- src/pages/iban/detail/IbanDetailPage.tsx
This PR is related to [this one](https://github.com/pagopa/pagopa-selfcare-frontend/pull/289) previously closed. The changes made are related to another bug on BO frontend portal when the IBAN that will reveals itself when an IBAN is updated. The bug does not permits the correct update because the Frontend portal was sending a wrong body request to BO backend.
- Linearized various intermediate models in order to gain a common interface for IBAN update.
This change is required in order to correctly perform the update on IBANs
- Tested in DEV environment
expected)
> fix: resolved wrong generation of request body in IBAN updates

- package.json
- src/api/BackofficeClient.ts
- src/api/__tests__/PortalApiClient.test.ts
- src/components/Header.tsx
- src/components/SideMenu/SideMenu.tsx
- src/hooks/useSelectedParty.tsx
- src/hooks/useSigninData.tsx
- src/locale/it.json
- src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/iban/list/IbanTable.tsx
- src/pages/stations/addEditStation/components/AddEditStationFormValidation.tsx
- src/pages/stations/detail/StationDetailPage.tsx
- src/pages/stations/detail/components/StationDetailsValidation.tsx
- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- src/services/__mocks__/channelService.ts
- src/services/__tests__/channelService.test.ts
- src/services/channelService.ts
- 🛠️ fix for associating an Creditor Institution to a Station
- now we call the right `GET` service
- 🆎 fix `GPD` label
- 🗒️  removed `console.log`
bug-fixing
- manually
expected)
> [PASELC-590] fix delegation for Stations

- src/pages/stations/stationAssociateEC/ECAccountItemSelection.tsx
- src/pages/stations/stationAssociateEC/ECSelectionSearch.tsx
- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- src/services/__mocks__/channelService.ts
> Paselc 646 associa ec con il campo sbagliato

- package.json
- src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- src/services/nodeService.ts
> [PASELC-675] fix: add 'itself' as associable institution for stations and channels

- src/api/BackofficeClient.ts
- src/model/Station.tsx
- src/pages/channels/addEditChannel/AddEditChannelForm.tsx
- src/pages/channels/addEditChannel/components/AddEditChannelValidationForm.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/services/stationService.ts
- src/utils/station-utils.ts
> [PASELC-684] fix: resolved bug on station check

- src/model/RolePermission.ts
- src/pages/dashboard/components/DownloadSection.tsx
This PR includes some changes made before releasing on UAT and PROD environment
- Temporarely disabled creditor institution export
- Added iban export's button disabling if no data found
These changes are required in order to align the last edits for releaase.
expected)
> [PASELC-716] chore: Updates before minor release

- integration-test/00_login.js
- public/index.html
- src/components/Header.tsx
- src/model/RolePermission.ts
- src/model/__tests__/Product.test.ts
renamed `pagoPa` string with `pagoPA`
expected)
> [PASELC-726] name pagoPa

- .github/workflows/release_deploy.yml
- package.json
- src/api/BackofficeClient.ts
- src/services/stationService.ts
- Resolved bug on parsing object in ProblemJson object
- Resolved bug on GitHub pipeline when PR is merged and automatic deploy is performed without environment variable
- Tested in DEV environment
expected)
> fix: resolved error with ProblemJson object

- package.json
- src/pages/stations/stationAssociateEC/ECSelectionSearch.tsx
- src/utils/env.ts
> fix: added tax code search on available CIs for station

- package.json
- src/api/BackofficeClient.ts
- src/locale/it.json
- src/pages/stations/detail/components/StationDetails.tsx
- src/pages/stations/detail/components/StationDetailsValidation.tsx
> [PASELC-735] feat: added station version field in station detail

- src/App.tsx
- src/components/SideMenu/SideMenu.tsx
- src/model/RolePermission.ts
- Added Route privileges check for every route
- Changed navbar "Pacchetto commissioni" permission check
[VAS-679](https://pagopa.atlassian.net/browse/VAS-679?atlOrigin=eyJpIjoiNzI4NWJiNzdiNDA5NDM3MWI4MDRmMWFhMGU0MTc0ZjkiLCJwIjoiaiJ9)
expected)
[VAS-679]: https://pagopa.atlassian.net/browse/VAS-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-679] fix: Protected all routes that needed privileges

- src/api/BackofficeClient.ts
- src/components/SideMenu/SideMenu.tsx
- src/locale/it.json
- src/pages/commisionalPackages/CommissionPackagesPage.tsx
- src/pages/commisionalPackages/list/CommissionPackagesTable.tsx
- src/pages/commisionalPackages/list/CommissionPackagesTableColumns.tsx
- src/services/__mocks__/commissionPackageService.ts
- src/services/bundleService.ts
- Implemented API getBundlesByPSP from [pagopa-selfcare-ms-backoffice-backend](https://github.com/pagopa/pagopa-selfcare-ms-backoffice-backend)
- Cleaned code
[VAS 540](https://pagopa.atlassian.net/browse/VAS-540?atlOrigin=eyJpIjoiZDk5YTNhNWU4NTFiNGZlN2E5ZWY1MTk2YTFiN2E1NGIiLCJwIjoiaiJ9)
expected)
> [VAS-540] feat: Implement getBundlesByPSP

- src/pages/iban/IbanPage.tsx
- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- fixed validity and due date checks on iban create
- fixed date default
expected)
> [VAS-721] fix: Validity date check on iban create

- src/pages/commisionalPackages/list/CommissionPackagesTableColumns.tsx
- Commission package item menu on DataGrid are now dynamic based on the package type
[VAS-736](https://pagopa.atlassian.net/browse/VAS-736?atlOrigin=eyJpIjoiZWUzMzkyYjk3NjcwNDE5NjhmNGM1Mjc4ZjhmMWRiYzUiLCJwIjoiaiJ9)
expected)
[VAS-736]: https://pagopa.atlassian.net/browse/VAS-736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-736] Implemented dynamic package item table action menu

- integration-test/05_operationTable_addEdit.js
- integration-test/run_integration.sh
- package.json
- src/App.tsx
- src/model/RolePermission.ts
- src/pages/dashboard/DashboardPage.tsx
- granted read/write permission on operation table box to EC direct, PSP direct and PT
expected)
> [VAS-744] fix: Operation table box permissions

- src/api/BackofficeClient.ts
- src/pages/channels/addEditChannel/AddEditChannelPage.tsx
- src/services/__mocks__/channelService.ts
- src/services/__mocks__/nodeService.ts
- src/services/channelService.ts
- src/services/nodeService.ts
- Changed getFirstValidChannelCode API input from pspCode to taxCode
[VAS-695](https://pagopa.atlassian.net/browse/VAS-695?atlOrigin=eyJpIjoiNWZjOTJmMzUzMzVhNGQzMzg5Yjg3ZjVhZWNkNWVkODMiLCJwIjoiaiJ9)
expected)
[VAS-695]: https://pagopa.atlassian.net/browse/VAS-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-695] Changed getFirstValidChannelCode API path param

- src/locale/it.json
- Fixed iban page's text from `Dati ente crerditore `to `Dati ente creditore`
[VAS-770](https://pagopa.atlassian.net/browse/VAS-770?atlOrigin=eyJpIjoiYTI5NWM5OWJmNjMyNGNhMTg2NTFiZGQzYTYxZTEzOWQiLCJwIjoiaiJ9)
expected)
[VAS-770]: https://pagopa.atlassian.net/browse/VAS-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-770] Fixed iban title tag

- .github/workflows/release_deploy.yml
- src/App.tsx
- src/locale/it.json
- src/pages/maintenance/MaintenancePage.tsx
- Added Maintenance page
- Added env to show the maintenance page
[VAS-802](https://pagopa.atlassian.net/browse/VAS-802?atlOrigin=eyJpIjoiMjAwNTMwMTRkOTE4NDAyMjhiMmI5ZmU5Yjk4OWRhZDAiLCJwIjoiaiJ9)
expected)
[VAS-802]: https://pagopa.atlassian.net/browse/VAS-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-802] Added Maintenance page

- .github/workflows/release_deploy.yml
> chore: add mantainance flag on prod

- src/components/CommonHeader/CommonHeader.tsx
- added `productId` query param on redirect for opening zendesk ticket
https://pagopa.atlassian.net/wiki/spaces/SCP/pages/824148657/Integrazione+webform+Zendesk 
expected)
> [VAS-508] feat: Add productId query param on assistence redirect

- openApi/scripts/api-portal_fixPostGen.js
- Fixed generated apis through post script update
expected)
> fix: generated types

- package.json
- src/locale/it.json
- src/pages/commisionalBundles/__tests__/list/CommissionBundlesTableColumns.test.tsx
- src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
- src/utils/common-utils.ts
- Removed amount range from commission bundle table columns
- Added state chip to commission bundle table columns
- Improved unit tests
- Added new utility methods
[VAS-803](https://pagopa.atlassian.net/browse/VAS-803?atlOrigin=eyJpIjoiMDkwMmYyMTRmZDlhNGM4ZjgxNDZhMDJmYWQ3NjJmZmEiLCJwIjoiaiJ9)
Written unit tests for the new code
expected)
[VAS-803]: https://pagopa.atlassian.net/browse/VAS-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-803] Introduced bundle state chip

- src/locale/it.json
- src/pages/iban/list/IbanTableColumns.tsx
- added column due date in iban table
expected)
> [VAS-855] feat: Add column due date in iban table

- src/pages/dashboard/components/ECRegistrationData.tsx
- removed accession date from creditor institute dashboard page
expected)
> [VAS-845] feat: Remove accession date from ec dashboard page

- src/hooks/useSigninData.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- yarn.lock
- Fixed pspCode creation on node signing
https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-860
Tested on local instance pointing at DEV environments, using the psp selectable parties (PS Signed, PSP Signed DEMO..)
expected)
> [VAS-860] fix: wrong psp code on node signin

- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
- src/utils/common-utils.ts
- Added util method to validate IBANs
- Changed iban validation in iban creation form
[VAS-309](https://pagopa.atlassian.net/browse/VAS-309?atlOrigin=eyJpIjoiYjU2OWRkOGNmYTU1NDA1OWE4MmVjNTdhMmI1Zjg4YzYiLCJwIjoiaiJ9)
expected)
[VAS-309]: https://pagopa.atlassian.net/browse/VAS-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-309] feat: Defined iban validation algorithm

- src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
- src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
- fixed creditor institution tax code path parameter value
- fixed update iban logic
expected)
> [VAS-872] fix: Stand in  and cup selection

- src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
- fixed StandIn and CUP iban selection edge case
expected)
> fix: StandIn and CUP iban selection edge case

- .github/workflows/code_review.yml
- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
- src/utils/client-utils.ts
- src/utils/common-utils.ts
- Fixed createIban response handling both in case of success and error conflict
- Improved unit tests
The iban creation was not working correctly
expected)
> fix: Create iban response handling

- .env.development.local
- src/locale/it.json
- src/pages/stations/stationECList/StationECTable.tsx
- src/pages/tos/TOS.tsx
- Set TOS content to temporary maintenance description
- Updated remove ec popup content
https://pagopa.atlassian.net/browse/VAS-775
https://pagopa.atlassian.net/browse/VAS-890
expected)
> [VAS-775][VAS-890] feat: minor changes

- src/locale/it.json
- src/pages/apiKeys/AddApiKeyPage.tsx
- src/pages/channels/addEditChannel/AddEditChannelForm.tsx
- src/pages/channels/addEditChannel/AddEditChannelPage.tsx
- src/pages/channels/channelAssociatePSP/ChannelAssociatePSPPage.tsx
- src/pages/channels/detail/ChannelDetailPage.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- src/pages/iban/addEditIban/__tests__/AddEditIbanForm.test.tsx
- src/pages/paymentsReceipts/list/PaymentsReceiptsTable.tsx
- src/pages/paymentsReceipts/list/__tests__/PaymentsreceiptsTable.test.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
- src/utils/client-utils.ts
- Fixed error message bug when receiving status code 404 or 409 when associating an EC to a station
- Added error handling to payments receipts APIs
- Aligned alert error title translation
[VAS-887](https://pagopa.atlassian.net/browse/VAS-887?atlOrigin=eyJpIjoiZmE4ZGE1MTQ2OTEzNGZjNjg4ODY3OGE3YjdkOTFhYTIiLCJwIjoiaiJ9)
expected)
[VAS-887]: https://pagopa.atlassian.net/browse/VAS-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-887] fix: Fixed APIs' error handling

- src/pages/stations/stationECList/StationECTable.tsx
> fix: modal ecName

- src/pages/paymentsReceipts/list/PaymentsReceiptsTable.tsx
- Hided pagination in CUP's data grid
Pagination shouldn't be visible
expected)
> fix: Hide pagination CUP

- src/api/BackofficeClient.ts
- src/locale/it.json
- src/model/Node.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPage.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPage.test.tsx
- src/pages/dashboard/nodeSignIn/components/CommonRadioGroup.tsx
- src/pages/delegations/detail/DelegationDetailPage.tsx
- src/services/__mocks__/channelService.ts
- src/services/__mocks__/stationService.ts
- src/services/__tests__/brokerService.test.ts
- src/services/__tests__/pspBrokerService.test.ts
- src/services/brokerService.ts
- src/services/pspBrokerService.ts
- enabled direct/undirect connection flag on registration data update for CI/PSP/PT when station/channels have not been created
- delete broker on switch from direct to undirect connection
- update tests
depends on [PR#359](https://github.com/pagopa/pagopa-selfcare-ms-backoffice-backend/pull/359)
expected)
> [VAS-844] feat: Enable direct/undirect connection flag

- src/pages/delegations/list/DelegationsTableColumns.tsx
- src/services/__mocks__/brokerService.ts
- used `is_institution_signed_in` field instead of `cbill_code` field to enable/disable navigation button to delegation detail page
depends on [PR#360](https://github.com/pagopa/pagopa-selfcare-ms-backoffice-backend/pull/360)
expected)
> [VAS-929] fix: Logic on go to delegation detail button

- src/api/BackofficeClient.ts
- src/pages/paymentsReceipts/list/PaymentsReceiptsTableColumns.tsx
- src/pages/paymentsReceipts/list/__tests__/PaymentsreceiptsTable.test.tsx
- Fixed filter date getPaymentsReceipts
- Added format date value to CUP's table column
Filtering by date didn't work
expected)
> fix: CUP Payments Receipts filter date & format date

- src/api/BackofficeClient.ts
- src/components/Table/TableSearchBar.tsx
- src/components/Table/__tests__/TableSearchBar.test.tsx
- src/locale/it.json
- src/model/PaymentsReceipts.ts
- src/pages/paymentsReceipts/PaymentsReceiptsPage.tsx
- src/pages/paymentsReceipts/list/PaymentsReceiptsTable.tsx
- src/services/__mocks__/paymentsReceiptsService.ts
- src/services/paymentsReceiptsService.ts
- Added new params to getPaymentsreceipts API method 
- Implemented pagination to CUP's table
[VAS-914](https://pagopa.atlassian.net/browse/VAS-914?atlOrigin=eyJpIjoiNDg0YTBiY2Q3YWJkNDU1ZWE0YjJiNWI3NTliZTE0MzkiLCJwIjoiaiJ9)
expected)
[VAS-914]: https://pagopa.atlassian.net/browse/VAS-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-914] feat: Implement debtorOrIuv CUP filter and pagination

- package.json
- src/api/BackofficeClient.ts
- src/pages/stations/__tests__/AddEditStationForm.test.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/services/__tests__/stationService.test.ts
- src/services/stationService.ts
- Introduced rework for station testing
- Updated unit testing
https://pagopa.atlassian.net/browse/VAS-964
expected)
> [VAS-964] feat: reworked station testing to include different types

- src/pages/stations/addEditStation/AddEditStationForm.tsx
> fix: cert test failure label on station testing

- src/api/BackofficeClient.ts
- updated client
depends on [PR#374](https://github.com/pagopa/pagopa-selfcare-ms-backoffice-backend/pull/374)
expected)
> [VAS-1005] chore: Updated client

- .github/workflows/release_deploy.yml
- package.json
- src/components/CommonHeader/MyHeaderProduct.tsx
💇‍♀️ new style for operator header
- added the drawer
_we have some limitations, for example we don't have the url logo of the oranization_
🐛  fixed the select if there are more than one option
Improvement
expected)
> new style for MyHeaderProduct

- src/api/BackofficeClient.ts
- src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsTable.tsx
- src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleSubscriptionsTable.test.tsx
- src/services/bundleService.ts
- updated accept and reject public subscription API call with the necessary param to notify via email
depends on [PR#375](https://github.com/pagopa/pagopa-selfcare-ms-backoffice-backend/pull/375)
expected)
> [VAS-955] feat: Updated accept and reject public subscription API 

- src/pages/delegations/detail/DelegationDetailPage.tsx
- enabled payment contacts section in delegation page
expected)
> [VAS-1006] feat: Eable payment contacts section

- .github/release.yml
- .github/workflows/check_pr.yml
- .github/workflows/release_deploy.yml
:octocat: new github action for checking the labels
🧠 new logic -> prerelease if deploy!=prod
🖊️  To improve the changelog on [Github](https://github.com/pagopa/pagopa-selfcare-frontend/releases/tag/1.20.26)
expected)
> prerelease

- src/locale/it.json
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- Change bundle types italian transaltion:
- "Globali" -> "Per tutti"
- "Privati" -> "Su invito"
- "Pubblici" -> "Su richiesta"
[VAS-1033](https://pagopa.atlassian.net/browse/VAS-1033?atlOrigin=eyJpIjoiOWI4YTBmMzk0MjQ2NGMxYTgyMzY5NTViMDk0MmMyNjAiLCJwIjoiaiJ9)
expected)
[VAS-1033]: https://pagopa.atlassian.net/browse/VAS-1033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-1033] feat: Change bundle types italian translation

- package.json
- src/hooks/useOrganizationType.ts
- src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- 🐛 bug fix side menu
- 📦 fix create bundle
expected)
> hostfix org type and roles

- src/locale/it.json
- Changed create bundle message it translation to remove bundle type
[VAS-1033](https://pagopa.atlassian.net/browse/VAS-1033?atlOrigin=eyJpIjoiOGM1ZjljODBhYjA2NDExMGFkNTE5ZTI3MDc1OGM1ZGUiLCJwIjoiaiJ9)
expected)
[VAS-1033]: https://pagopa.atlassian.net/browse/VAS-1033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Change create bundle message it translation

- src/locale/it.json
- src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/BundleTaxonomiesTable.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
- src/services/__mocks__/bundleService.ts
- Changed titles and messages to differentiate edit mode from create mode in Bundle's add/edit page
- Fixed add/edit taxonomies
- The text was always describing the creation of a bundle and not the editing
- Taxonomies weren't working correctly
expected)
> fix: Translation for bundle edit page & taxonomy bug

- .env.development.local
- .github/workflows/release_deploy.yml
the latest version on github is only the prod release
expected)
> New inputs for GHA Release and Deploy

- package.json
- src/api/BackofficeClient.ts
- src/pages/stations/__tests__/AddEditStationForm.test.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/addEditStation/AddEditStationPage.tsx
- src/pages/stations/detail/StationDetailPage.tsx
- src/services/__mocks__/stationService.ts
- src/services/stationService.ts
- src/utils/station-utils.ts
- Implemented isConnectionSync flag from backend's station details
- Cleaned code
[VAS-1009](https://pagopa.atlassian.net/browse/VAS-1009?atlOrigin=eyJpIjoiYjQwYmZjYzkzZWFjNGQ2Yjg2ZmMwNDdmMjE2OWE5MmUiLCJwIjoiaiJ9)
expected)
[VAS-1009]: https://pagopa.atlassian.net/browse/VAS-1009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-1009] feat: Implement station sync flag from Backend

- src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
- Removed validation that was preventing the user to insert the commission fee as 0€
[VAS-1051](https://pagopa.atlassian.net/browse/VAS-1051?atlOrigin=eyJpIjoiZTY1NDQwOTc5MjhmNDlhY2JkYmY3YWU3MWYwOGJkOWEiLCJwIjoiaiJ9)
expected)
[VAS-1051]: https://pagopa.atlassian.net/browse/VAS-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-1051] feat: Permit bundle's commission fee to be zero

- src/api/BackofficeClient.ts
- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- src/pages/stations/stationAssociateEC/__tests__/StationAssociateECPage.test.tsx
- src/services/__mocks__/stationService.ts
- src/services/__tests__/stationService.test.ts
- src/services/stationService.ts
- integrated new response model for get segregation code api
depends on https://github.com/pagopa/pagopa-selfcare-ms-backoffice-backend/pull/394
[VAS#1050](https://pagopa.atlassian.net/browse/VAS-1050)
expected)
> [VAS-1050] Updated get segregation code API

- .github/workflows/cd_main.yml
- .github/workflows/cd_next.yml
- .github/workflows/check_pr.yml
- .github/workflows/ci_code_review.yml
- .github/workflows/ci_integration_test.yml
- .github/workflows/deploy_on_cdn.yml
- .github/workflows/github_scripts/check_required_labels.js
- .github/workflows/github_scripts/check_size.js
- .github/workflows/github_scripts/check_source_branch.js
- .github/workflows/github_scripts/make_latest_release.js
- .github/workflows/github_scripts/update_code.js
- .github/workflows/release_deploy.yml
- .github/workflows/update_code.yml
- .github/workflows/update_gha.py
- integration-test/features/step_definitions/download_pem.sh
gitflow light
https://pagopa.atlassian.net/wiki/spaces/VAS/pages/1079410801/GitFlow+Light
expected)
> new actions

- package.json
- yarn.lock
> Release 1.22.0

- src/pages/iban/addEditIban/AddEditIbanForm.tsx
- src/utils/common-utils.ts
- Trimmed iban empty spaces
API create iban was responding with error when user was sending iban with empty spaces at the end
Manual testing
expected)
> [VAS-1068] fix: Iban trim empty spaces

- package.json
- src/api/BackofficeClient.ts
- src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
- src/services/bundleService.ts
- updated private bundle offer API with new parameters
expected)
> [VAS-1108] feat: Update delete offer API

- package.json
- src/api/BackofficeClient.ts
- src/locale/it.json
- src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
- src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
- src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailActivationPage.test.tsx
- src/pages/commisionalBundles/detail/__tests__/CommissionBundleDetailPage.test.tsx
- src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
- src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleDetailSubscriptionsTable.test.tsx
- src/services/__mocks__/bundleService.ts
- src/services/__tests__/bundleService.test.ts
- src/services/bundleService.ts
- Implemented APIs to reject & accept offers by Creditor institutions
[VAS-1069](https://pagopa.atlassian.net/browse/VAS-1069?atlOrigin=eyJpIjoiOTlmMTgyM2I2YTRhNGIzNWJkYmUxZDU3MTFlMWU1NDAiLCJwIjoiaiJ9)
Unit test & manual testing
expected)
[VAS-1069]: https://pagopa.atlassian.net/browse/VAS-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-1069] feat: Implement APIs accept/reject offers

- package.json
- src/components/Table/TableDataGrid.tsx
- src/components/Table/TableEmptyState.tsx
- src/locale/it.json
- src/model/CommissionBundle.ts
- src/pages/commisionalBundles/CommissionBundlesPage.tsx
- src/pages/commisionalBundles/detail/components/subscriptions/__tests__/CommissionBundleDetailSubscriptionsTable.test.tsx
- src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
- src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
- src/pages/commisionalBundles/list/__tests__/CommissionBundlesTable.test.tsx
- src/pages/commisionalBundles/list/__tests__/CommissionBundlesTableColumns.test.tsx
- Improved generic table empty state component
- Changed generic datagrid component to use the noRowsOverlay property to render the empty state
[VAS-1114](https://pagopa.atlassian.net/browse/VAS-1114?atlOrigin=eyJpIjoiMmNiYmUzMjMxMjYxNDFhNGJkZmQyODhhNmZlOGUzNWMiLCJwIjoiaiJ9)
Needed to change the state filter on CI's private bundle table
expected)
[VAS-1114]: https://pagopa.atlassian.net/browse/VAS-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-1114] feat: Refactor private bundles state filter

- src/locale/it.json
- src/pages/stations/detail/components/StationDetails.tsx
- Modified StationsDetails page to change dynamically the StationDetails page subtitle based on station wrapper status
Wrong subtitle when the station was in status approved
[VAS-1115
](https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-1115)
Manual testing
expected)
> [VAS-1115] fix: Change dynamically the StationDetails page subtitle based on station wrapper status

- src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
- fixed abi value on bundle creation
expected)
> hotfix: ABI logic

- package.json
- src/api/BackofficeClient.ts
- src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
- src/services/__tests__/bundleService.test.ts
- src/services/bundleService.ts
- updated `DELETE /bundles/{id-bundle}/payment-service-providers/{psp-tax-code}` with new parameters
depends on https://github.com/pagopa/pagopa-selfcare-ms-backoffice-backend/pull/433
[VAS#1108](https://pagopa.atlassian.net/browse/VAS-1108)
expected)
> [VAS-1108] feat: Update delete bundle api

- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
> hotfix bic signin

- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
> exclude N/A as a valid ABI code

- src/pages/notices/detail/PaymentNoticesDetailPage.tsx
> fix: notices ci detail

- src/pages/stations/addEditStation/AddEditStationForm.tsx
- added missing call to API `PUT /stations/wrapper/{station-code}` on submit for station in status `TO_FIX_UPDATE`
[VAS#1128](https://pagopa.atlassian.net/browse/VAS-1128)
expected)
> hotfix: Stations in status TO_FIX_UPDATE

- .github/workflows/ci_code_review.yml
- README.md
- package.json
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- yarn.lock
- Merged main into next 
Bring into the branch next the hotfixes made to the stations 
expected)
> chore: Merge main into next

- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
- src/services/__mocks__/institutionsService.ts
- changed the bundle creation page to fix a bug
expected)
> Hotfix Bundle Banco Sardegna 

- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
- src/services/__mocks__/bundleService.ts
- src/utils/channel-utils.ts
> fix: psp bundle list and idBrokerPsp

- src/locale/it.json
> fix: Missing translate

- src/model/Channel.tsx
- src/model/CommissionBundle.ts
- src/pages/channels/addEditChannel/AddEditChannelForm.tsx
- src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
- src/pages/channels/addEditChannel/components/AddEditChannelValidationForm.tsx
- src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
- src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
- Modified Channels' new connectivity checkbox and select in edit page
- Fixed graphic bug where a checkbox was misaligned with the other checkbox
- Hidden bundle's delete button when the bundle is already been deleted or is expired
- Disabled invite EC's button in bundle detail page when the bundle is already been deleted or is expired
Fix pre-release
expected)
> fix: Bugs found before release

- .github/workflows/ci_integration_test.yml
- .gitignore
- .identity/00_data.tf
- .identity/03_github_environment.tf
- .identity/download_pem.sh
- clean integration test action code
- run terraform apply
[VAS#1196](https://pagopa.atlassian.net/browse/VAS-1196)
expected)
> hotfix: Integration test action

- src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
📦 bundle GEC create/edit: changed the minimum date value (now + 2d) for the filed dateFrom
expected)
> [VAS-1203] hotfix bundle date from

- src/locale/it.json
> fix: error boundary label

- src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
- avoid check on station and channel on new Nodo registrations
[PPANTT-87](https://pagopa.atlassian.net/browse/PPANTT-87)
expected)
[PPANTT-87]: https://pagopa.atlassian.net/browse/PPANTT-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> hotfix: Node sign in  on new registration

- package.json
- src/App.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
- src/pages/tos_and_privacy/TOS_AND_PRIVACY.tsx
- src/pages/tos_and_privacy/__tests__/TOS_AND_PRIVACY.test.tsx
> Merge main next 1.29.3

- src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
> fix: hasPoste flag management of related data

- package.json
- src/locale/it.json
- src/model/ApiKey.tsx
- src/model/__tests__/ApiKey.test.tsx
- Added new ACA product to api keys
- Updated unit test
[PPANTT-93](https://pagopa.atlassian.net/browse/PPANTT-93)
expected)
[PPANTT-93]: https://pagopa.atlassian.net/browse/PPANTT-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-93] feat: Add api key ACA 

- .github/workflows/ci_integration_test.yml
- e2e/tests/delegations.spec.ts
- Defined new e2e test with playwright for the Delegations' page flow
- Changed GHA e2e test cron schedule
[PPANTT-9](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-9)
Local testing
expected)
[PPANTT-9]: https://pagopa.atlassian.net/browse/PPANTT-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-9] feat: e2e delegations' page

- src/api/BackofficeClient.ts
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/__tests__/AddEditCommissionBundleForm.test.tsx
- Changed in the create/edit bundle page the channels's autocomplete filtering from client-side to server-side
[PPANTT-26](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-26)
Unit & e2e tests
expected)
[PPANTT-26]: https://pagopa.atlassian.net/browse/PPANTT-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-26] feat: Bundle's channel list server-side autocomplete

- src/pages/channels/detail/components/ChannelDetails.tsx
- src/pages/channels/list/ChannelsTable.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- Hidden the Channel's & Station's endpoints values in detail page when the main target path is empty
- Fixed Channels' tables pagination
expected)
> hotfix: Channels & Stations endpoint visualization & Channel's pagination

- e2e/tests/privateBundles.spec.ts
- Fixed private bundles e2e tests
expected)
> fix: Private bundles e2e

- src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleDetailSubscriptionsTable.tsx
-  Fixed pagination bundle's subscription table pt2
expected)
> hotfix: Pagination bundle's subscription table pt2

- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
- src/utils/common-utils.ts
- Fixed conversion bug for currency string both in Bundle's creation and EC's bundle activation
[PPANTT-128](https://pagopa.atlassian.net/browse/PPANTT-128)
When a user input in currency textfield values like "4.15" it was converted as number cent "414.9999999" and sent like that to the backend. Now the values are rounded to the nearest integer so "414.9999" becomes "415" and "115.000006" becomes "115"
Manual testing
expected)
[PPANTT-128]: https://pagopa.atlassian.net/browse/PPANTT-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Currency format from string to number cent - float conversion bug

- .github/workflows/check_pr.yml
- src/utils/constants.ts
- Re-enabled "PO" bundles' payment type
- Disabled check on source branch on GHA
[PPANTT-130](https://pagopa.atlassian.net/browse/PPANTT-130)
expected)
[PPANTT-130]: https://pagopa.atlassian.net/browse/PPANTT-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-130] feat: Re-enable "PO" payment type

- src/locale/it.json
- src/model/Channel.tsx
- src/model/Station.tsx
- src/pages/commisionalBundles/CommissionBundlesPage.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- src/services/__mocks__/stationService.ts
- src/utils/station-utils.ts
- Create/Edit station page:
- Added new field "REST Endpoint"
- Added new switch to toggle on and off "payment options"
- Station Detail Page:
- Added new field "REST Endpoint"
- Added new boolean field for "payment options"
- Updated unit tests 
[PPANTT-72](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-72)
expected)
[PPANTT-72]: https://pagopa.atlassian.net/browse/PPANTT-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-72] feat: Station REST services configuration

- src/api/BackofficeClient.ts
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- Added fields `restEndpoint`& `isPaymentOptionsEnabled` to createStation EC's API
When an EC created a Station the above-mentioned field weren't saved
expected)
> fix: Create station payment options fields

- package.json
- src/api/BackofficeClient.ts
- src/pages/channels/addEditChannel/AddEditChannelForm.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/services/__mocks__/stationService.ts
- Updated flag standIn properties to channel and stations
[PPANTT-138](https://pagopa.atlassian.net/browse/PPANTT-138?atlOrigin=eyJpIjoiMjFhY2Y3OWZlOGU2NDBmMTg2YTFiMjUxMmQ4Zjk5NDgiLCJwIjoiaiJ9)
expected)
[PPANTT-138]: https://pagopa.atlassian.net/browse/PPANTT-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-138] feat: Add flagStandIn to Channel & Station models

- package.json
- src/components/WrapperCommon/GetAlert.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/addEditStation/__tests__/AddEditStationForm.test.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- src/pages/stations/detail/components/__tests__/StationDetails.test.tsx
- src/utils/station-utils.ts
Added feature flags:
- Flag to hide/show the REST endpoint section in Station's detail/add/edit pages
- Flag to hide/show the Payment Options service section in Station's detail/add/edit pages
expected)
> fix: Implement feature flags for Station's REST endpoint & ODP sections

- package.json
- src/components/WrapperCommon/GetAlert.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
- src/pages/stations/addEditStation/AddEditStationForm.tsx
- src/pages/stations/addEditStation/__tests__/AddEditStationForm.test.tsx
- src/pages/stations/detail/components/StationDetails.tsx
- src/pages/stations/detail/components/__tests__/StationDetails.test.tsx
- src/utils/bundle-utils.ts
- src/utils/station-utils.ts
- updated taxonomy extraction
expected)
> [PPANTT-151] feat: Updated taxonomy extraction

- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleTaxonomies.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/drawer/BundleTaxonomiesDrawer.tsx
- src/utils/bundle-utils.ts
- Updated taxonomy extraction
expected)
> Ppantt 151 feat update taxonomy extraction

- src/model/Channel.tsx
- src/model/Station.tsx
- src/pages/channels/addEditChannel/__tests__/AddEditChannelForm.test.tsx
- Fixed Channel forwarder url
- Fixed Station dev forwarder url
expected)
> [PPANTT-156] fix: Channel forwarder url & Station dev forwarder url

- .github/workflows/ci_code_review.yml
- package.json
- src/api/BackofficeClient.ts
- src/components/CommonHeader/MyHeaderProduct.tsx
- src/components/CommonHeader/__tests__/CommonHeader.test.tsx
- src/components/CommonHeader/__tests__/MyHeaderProduct.test.tsx
- src/components/Header.tsx
- src/hooks/useParties.tsx
- src/hooks/useSelectedParty.tsx
- src/model/Party.tsx
- src/redux/slices/partiesSlice.ts
- src/services/__mocks__/institutionsService.ts
- src/services/__mocks__/partyService.ts
- src/services/__tests__/institutionService.test.ts
- src/services/__tests__/partyService.test.ts
- src/services/institutionService.ts
- src/services/partyService.ts
- Rework getInstitution
expected)
> Next release 1.37

- src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
- Updated checks to avoid submit on missing logo
- Fixed reference to wrong translate label on error
expected)
> [PPANTT-173] fix: check on logo

- src/model/ApiKey.tsx
- src/model/__tests__/ApiKey.test.tsx
- src/pages/apiKeys/AddApiKeyPage.tsx
- Changed institution type check to conditionally render the apikeys' list
[PPANTT-175](https://pagopa.atlassian.net/browse/PPANTT-175)
expected)
[PPANTT-175]: https://pagopa.atlassian.net/browse/PPANTT-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-175] fix: PT api key list

- integration-test/tests/utils/e2eUtils.ts
- Reverted delete e2e Marketplace be url
Faultily deleted marketplace be url from e2e tests
expected)
> fix: Revert delete e2e Marketplace be url

- .github/workflows/ci_integration_test.yml
- Fixed e2e GHA upload report folder
e2e GHA broke on report upload
expected)
> fix: e2e GHA upload report folder

- src/locale/it.json
- change `ACA` api key name from `ACA - paCreatePosition` to `ACA - Conferimento delle posizioni debitorie`
[PPANTT-209](https://pagopa.atlassian.net/browse/PPANTT-209)
expected)
[PPANTT-209]: https://pagopa.atlassian.net/browse/PPANTT-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-209] chore: Change ACA api key label

- integration-test/tests/stations.spec.ts
- integration-test/tests/utils/bundleUtils.ts
- Changed button locator to dissociate EC from station
expected)
> fix: Integration test dissociate EC from station

- integration-test/tests/privateBundles.spec.ts
- Changed "Comune di Lorem Ipsum" with "Comune di Test"
expected)
> fix: Integration test change Comune Lorem Ipsum

- .github/workflows/deploy_on_cdn.yml
> chore: Add install azcopy

- integration-test/tests/stationMaintenances.spec.ts
- Defined Station Maintenances e2e tests
[PIDM-103](https://pagopa.atlassian.net/browse/PIDM-103?atlOrigin=eyJpIjoiMGQ0OTMyMjJhM2JiNDNjMDk0MGFhYTBhY2RmNDMwZjAiLCJwIjoiaiJ9)
expected)
[PIDM-103]: https://pagopa.atlassian.net/browse/PIDM-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIDM-103] feat: Station Maintenances e2e tests

- package.json
- src/components/SideMenu/SideMenu.tsx
- src/components/SideMenu/SideMenuLayout.tsx
- src/components/SideMenu/SidenavItem.tsx
- src/components/SideMenu/__tests__/SideMenu.test.tsx
[PIDM-218](https://pagopa.atlassian.net/browse/PIDM-218)
expected)
[PIDM-218]: https://pagopa.atlassian.net/browse/PIDM-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [PIDM-218]  Implemented collapsable side menu

- src/pages/iban/StandInAndCupForm/StandInAndCupForm.tsx
- src/pages/iban/StandInAndCupForm/__tests__/StandInAndCupForm.test.tsx
- fixed check when Standin or CUP iban are empty on first configuration attempt
[PIDM-271](https://pagopa.atlassian.net/browse/PIDM-271)
expected)
[PIDM-271]: https://pagopa.atlassian.net/browse/PIDM-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIDM-271] fix: Standin and CUP IBAN save on first configuration

- src/pages/notices/addEdit/PaymentNoticesAddEditForm.tsx
Fix error label refs for upload institution data form errors
Set right labels to be displayed in case of errors uploading institution data 
expected)
> fix: form error message translation label ref

- .github/workflows/ci_code_review.yml
- package.json
- src/api/BackofficeClient.ts
- src/pages/quicksight/QuicksightDashboardPage.tsx
- src/pages/quicksight/__tests__/QuicksightDashboardPage.test.tsx
- src/services/__tests__/quicksightDashboardService.test.ts
- src/services/quicksightDashboardService.ts
- added institutionId as query param if the user is a pagoPA operator
- updated unit tests
[PIDM-370](https://pagopa.atlassian.net/browse/PIDM-370)
expected)
[PIDM-370]: https://pagopa.atlassian.net/browse/PIDM-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIDM-370] fix: PSP dashboard for operator

- package.json
- src/locale/it.json
- updated Quicksight dashboard error message for admin user but not subscribed
[PIDM-379](https://pagopa.atlassian.net/browse/PIDM-379)
expected)
[PIDM-379]: https://pagopa.atlassian.net/browse/PIDM-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIDM-379] chore: Update Quicksight dashboard error message

- src/api/BackofficeClient.ts
- src/pages/stations/stationAssociateEC/StationAssociateECPage.tsx
- fixed model mapping in CI Station form
- mapped `applicationCode` and `mod4` field
- `auxDigit` avoid overwrite if value exist
[PIDM-348](https://pagopa.atlassian.net/browse/PIDM-348)
expected)
[PIDM-348]: https://pagopa.atlassian.net/browse/PIDM-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIDM-348] fix: Avoid information loss on CI station relation update

- integration-test/tests/utils/createJwt.ts
- integration-test/tests/utils/e2eUtils.ts
- Updated e2e test after jwt taxCode verification
[PIDM-441](https://pagopa.atlassian.net/browse/PIDM-441)
https://github.com/pagopa/pagopa-selfcare-ms-backoffice-backend/pull/550
expected)
[PIDM-441]: https://pagopa.atlassian.net/browse/PIDM-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [PIDM-441] Update e2e test after jwt taxCode verification

- CODEOWNERS
> chore: update codeowners with touchpoint team

- public/css/selfhostedfonts.css
- public/index.html
- removed import remote css `https://selfcare.pagopa.it/assets/font/selfhostedfonts.css`
- added new file _/public/css/selfhostedfonts.css_
To prevent files from external sources from being altered
expected)
> fix: [CHK-4138] local css import

- public/index.html
- Added a reference to a local CSS file (`css/selfhostedfonts.css`) in `public/index.html`.
The change was deployed to the development environment and verified to be working as expected.
expected)
> fix: [CHK-4138] ref local css in index.html

- .github/workflows/ci_code_review.yml
- .github/workflows/deploy_on_cdn.yml
- Introduced a `set -euo pipefail` directive to improve script safety.
- Quoted the `environment` input variable and stored it in `ENVIRONMENT` for better readability and to prevent shell injection.
- Replaced direct use of `${{ inputs.environment }}` in shell commands with the safe `ENVIRONMENT` variable.
This change mitigates a potential **shell injection vulnerability** 
- Manually tested the updated GitHub Actions workflow in a feature branch across `dev` env
expected)
> fix: [CHK-4139] GitHub run shell injection

- package.json
- src/hooks/useUserRole.ts
- src/pages/quicksight/QuicksightDashboardPage.tsx
The access to the Quicksight dashboard has been revised so that Psp Operators are also able to see and interact with it.
expected)
> feat:[PIDM-551]-Ruolo-Utente

- src/pages/delegations/detail/DelegationStationDetailsDrawer.tsx
- src/pages/delegations/detail/list/DelegationStationsTableColumns.tsx
- src/utils/common-utils.ts
- src/utils/station-utils.ts
- fixed mapping of `aux_digit` field
expected)
> fix: Delegation page aux digit mapping

- src/locale/it.json
- Typo "aggioranta" -> "aggiornata"
expected)
> fix: Typo "aggioranta"
