- src/pages/iban/detail/IbanDetailPage.tsx
- src/pages/iban/detail/__tests__/IbanDetailButtons.test.tsx
- src/pages/iban/detail/components/IbanDetailButtons.tsx
Change the delete button's function to redirect the user only after receiving the delete response.
The click on the 'Delete IBAN' button was redirecting the user to the IBANs page without waiting for the deletion to actually happen. Therefore, the just-deleted IBAN was still being displayed in the IBANs table. After a refresh, the IBANs table fetched the correct data.
manually
expected)
> PASELC-511 fix redirect to wait after iban delete

- src/locale/it.json
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPage.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInECForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPage.test.tsx
- src/services/__mocks__/nodeService.ts
- src/services/nodeService.ts
Update redux signin data after psp signin on the node so when redirecting user on dashboard, signin info will be freshly updated
After psp node signin, dashboard data wasn't updated
manually
expected)
> PASELC-537 refresh dashboard data after psp node signin

- src/hooks/useSigninData.tsx
- Fixed custom hook useSignInData to cover the case of getBrokerAndEcDetails returning null
- This fix is required because if the get of the ecDetails returns null and the get of pspBroker return the details, we were tryng to enter inside  a property of a null object, and this caused the problem where we were redirect inside of the catch case returning empty object instead of the psp broker details only.
expected)
> fix return value of ecBroker in case of get returns null

- src/pages/channels/channelAssociatePSP/PSPSelectionSearch.tsx
remove point-event: none from PSPSelectionSearch
When there is only a PSP available to be associated to the channel, the searchBox doesn't allow selection via click that PSP
expected)
> PASELC-593 fix psp selection search single item clickability

- README.md
- package.json
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
On PSP's sign-in process, in the related form the BIC code's text box was set in order to only accept 5-digit numerical codes (for example, 12345). This behavior is not correct because in specific situations, like with foreign PSPs, the BIC code can reach 11-character string in alphanumeric structure (for example BTI000IT001).
This fix is made in order to resolve this wrong setting, allowing the insertion of more complex BIC codes.
- Updated text box check, allowing 11-char codes instead of 5-digit codes
This PR was made in order to resolve the bug described before.
- Tested in DEV environment
expected)
> [PASELC-596] fix: resolved wrong BIC format

- openApi/portal-api-docs.json
- package.json
- src/pages/channels/detail/ChannelDetailPage.tsx
- src/pages/stations/detail/StationDetailPage.tsx
- src/services/__mocks__/channelService.ts
- src/services/__mocks__/stationService.ts
The retrieving of the number of associated channel for PSP and of associated station for EC in BO portal was wrong and the extracted value was the same value of the element that can be included in a paginated `get` operation. With this PR it was added a new field, named `total_items`, that permits to retrieve the correct number of elements filterable by paginated `get`.
- Added new field for actual total items value
This change is required in order to correctly show the counter values in BO portal
expected)
> [PASELC-595] fix: updated total items info

- README.md
- src/locale/it.json
- src/pages/components/ConfirmModal.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPage.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInECForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPSPForm.test.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPage.test.tsx
- src/pages/dashboard/nodeSignIn/components/CommonRadioGroup.tsx
This PR contains the definition of a modal that permits to confirm if a CI/PSP will connect directly or indirectly with Nodo system. The modal contains a message that permits the user to better understand the action that it is executing during the sign-in.
- Added confirmation modal on creditor institution's sign-in form for connection types with Nodo
- Added confirmation modal on payment service provider's sign-in form for connection types with Nodo
These changes are required in order to add a new popup during sign-in operation.
expected)
> [PASELC-508] feat: added modal for intermediation confirm

- openApi/portal-api-docs.json
- package.json
During several tests in UAT and PROD, a bug related to the registration steps was found and caused the institution to be unabled to proceed to use the BackOffice portal.
When the BackOffice Backend executed the logic related to API `utils/ec-brokers/{code}/details`, in some circumstances (i.e. the entities massively imported by SelfCare) the response contains an empty field `address`. This address is correctly set as optional for the Java model validator but was wrongly set as mandatory in the OpenAPI specs. This caused a wrong definition of the OpenAPI documentation that is used by BackOffice frontend in order to generate the models and the API used for communication with backend. So, when the frontend needs to set the sign-in content in local storage, an exception is thrown but a wrong …
> [PASELC-622] Error with CI/PSP already registered

- package.json
- src/pages/channels/list/ChannelsTableColumns.tsx
This PR contains the changes made on the special character set for the undefined channel dates. This char (the character '-') will not be used anymore for describe undefined dates and the empty column will describe this behavior furthermore.
- Removed standard char set in undefined channels dates
This change remove the not needed set of standard char for channels
- Tested in DEV environment
expected)
> [PASELC-660] fix: removed '-' char for channels' undefined dates

- src/pages/channels/detail/components/ChannelDetails.tsx
- src/pages/channels/detail/components/ChannelDetailsWrap.tsx
- src/pages/stations/list/StationsTableColumns.tsx
This PR contains the resolution of multiple bugs found after Go-Live event on BackOffice portal.
- Removed hand-cursor in stations table
- Added '/' char between target port and service path
The change are required in order to resolve open bugs found after Go-Live event
expected)
> [PASELC-663][PASELC-659] fix: resolved some bugs on frontend found after Go-Live event

- src/locale/it.json
- Changed label on EC-by-station search filter textbox
This change permits to resolve a wrong label, not correctly changed in previous PR
expected)
> fix: changed wrong label name on EC-by-station search

- src/App.tsx
- src/components/SideMenu/SideMenu.tsx
- src/hooks/usePermissions.ts
- src/locale/it.json
- src/model/RolePermission.ts
- src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/services/__mocks__/institutionsService.ts
- Changed broker list error message
- Added error message to channel API when retrieved list is empty
- Updated pages' permissions
Add/edit commission bundle page was displaying the wrong error message when the broker list was empty
expected)
> fix: Broker list error handling

- src/pages/commisionalBundles/__tests__/addEditCommissionBundles/AddEditCommissionBundleForm.test.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/components/AddEditCommissionBundleForm.tsx
- src/services/__mocks__/bundleService.ts
- src/services/__mocks__/institutionsService.ts
- Changed the property from which the broker tax code is retrieved
Broker code wasn't correctly passed to the API getChannels so it was returning all channels (instead of filtering by broker tax code) 
expected)
> fix: Fixed getChannels from broker tax code

- package.json
- src/pages/commisionalBundles/CommissionBundlesPage.tsx
- src/pages/commisionalBundles/__tests__/CommissionBundlesPage.test.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/AddEditCommissionBundlePage.tsx
- src/pages/commisionalBundles/addEditCommissionBundle/__tests__/AddEditCommissionBundlePage.test.tsx
- src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
- src/pages/commisionalBundles/detail/CommissionBundleDetailPage.tsx
- src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsDrawer.tsx
- src/pages/commisionalBundles/list/CommissionBundlesTable.tsx
- src/pages/delegations/detail/DelegationDetailPage.tsx
- src/pages/delegations/detail/__tests__/DelegationDetailPage.test.tsx
- src/redux/hooks.ts
- Fixed rendering of commission bundle's CI request fees, it was rendering "-" instead of 0
- The bundle table's tab value is now the type of the last bundle selected from the user in the redux state, when is not present the default is GLOBAL
- Removed the usage of the bundleId from the url params that could have caused security issues
- Added a new hook to redirect user to defined page when the requested redux state is empty
[VAS-1022](https://pagopa.atlassian.net/browse/VAS-1022?atlOrigin=eyJpIjoiM2M3ZmQ2ODA5MWVjNGNjZWFkMzExMjRmMjZjY2Y2YTQiLCJwIjoiaiJ9)
Unit tests
expected)
[VAS-1022]: https://pagopa.atlassian.net/browse/VAS-1022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-1022] fix: Improve user experience and solve security issues

- src/locale/it.json
- src/pages/commisionalBundles/detail/CommissionBundleDetailActivationPage.tsx
- src/pages/commisionalBundles/detail/components/CommissionBundleDetailTaxonomies.tsx
- src/pages/commisionalBundles/detail/components/subscriptions/CommissionBundleSubscriptionsDrawer.tsx
- src/services/__tests__/bundleService.test.ts
- src/services/bundleService.ts
- Implemented handling of empty CI's public bundle attributes as commission fee for all taxonomies in:
- CI's Bundle activation page
- CI's Bundle detail page
- PSP's Public Bundle subscription request drawer
[VAS-1030](https://pagopa.atlassian.net/browse/VAS-1030?atlOrigin=eyJpIjoiOWU2N2UyOGY5ZTY3NDZiY2I0ODlhM2IyZjQxMzVkY2UiLCJwIjoiaiJ9)
expected)
[VAS-1030]: https://pagopa.atlassian.net/browse/VAS-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-1030] feat: Implement "all taxonomy" commission fee

- src/pages/commisionalBundles/list/CommissionBundlesTableColumns.tsx
- Changed PSP bundle state logic to show state even if validityDateTo is undefined
Some bundles don't have the expire date and were causing the state chip to not render
expected)
> fix: PSP bundle state without validity date to

- src/components/TOS/TOSWall.tsx
- src/locale/it.json
- Aligned TOS page with UI design
[VAS-418](https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-418)
expected)
[VAS-418]: https://pagopa.atlassian.net/browse/VAS-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-418] feat: Align TOS page with UI design

- src/locale/it.json
- src/model/ApiKey.tsx
- src/model/__tests__/ApiKey.test.tsx
- src/pages/apiKeys/AddApiKeyPage.tsx
- src/pages/apiKeys/__tests__/AddApiKeyPage.test.tsx
- Added new config to generate new api key for printPaymentsNotice product
[VAS-1133](https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-1133)
expected)
[VAS-1133]: https://pagopa.atlassian.net/browse/VAS-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-1133] feat: Add new api key for printPaymentsNotice product

- src/locale/it.json
- fix modal label translate
expected)
> hotfix: ErrorBoundary labels 

- e2e/package.json
- e2e/tests/utils/bundleUtils.ts
- e2e/tests/utils/e2eUtils.ts
- e2e/yarn.lock
- Fixed the bundle's row selector that didn't work correctly after changing the bundle's min date from day after to three days after 
Fix integration tests
Manually
expected)
> hotfix: Fix bundle row selector e2e playwright

- .github/workflows/cd_main.yml
- .github/workflows/cd_next.yml
- .github/workflows/ci_code_review.yml
- .github/workflows/deploy_on_cdn.yml
- .github/workflows/release_deploy.yml
- package.json
- src/locale/it.json
- src/model/ApiKey.tsx
- src/model/__tests__/ApiKey.test.tsx
- src/pages/apiKeys/ApiKeysPage.tsx
- src/utils/env.ts
- Added new subscription for `FdR QI KPI` APIM product
- updated unit tests
- improved deploy's GHAs adding feature flag to the action inputs
[PPANTT-223](https://pagopa.atlassian.net/browse/PPANTT-223)
expected)
[PPANTT-223]: https://pagopa.atlassian.net/browse/PPANTT-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPANTT-223] feat: Add FdR QI KPI sub key

- src/locale/it.json
- src/pages/stationMaintenances/addEditDetail/StationMaintenanceAddEditDetail.tsx
- src/utils/common-utils.ts
- Adjust fromHours and toHours to handle GMT+2 to GMT+1 correctly
This update ensures that when a user enters a maintenance date, the portal correctly saves and displays the date while accounting for daylight saving time (DST) transitions. Previously, the system only considered GMT+2, which caused inconsistencies when users selected a date that falls within GMT+1 due to DST changes. This fix properly adjusts for these variations, ensuring accurate date storage and display.
Local testing
expected)
> [PIDM-160] fix(CreateStationMaintenance): Adjust fromHours and toHours to handle GMT+2 - GMT+1 correctly

- src/pages/dashboard/nodeSignIn/NodeSignInECForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPSPForm.tsx
- src/pages/dashboard/nodeSignIn/NodeSignInPTForm.tsx
- src/pages/dashboard/nodeSignIn/__tests__/NodeSignInPTForm.test.tsx
- src/pages/dashboard/nodeSignIn/components/CommonRadioGroup.tsx
- Fixed the following use case on node sign in form:
- EC -> avoid checks on existing stations if the selected institution is not a creditor institution broker
- PSP -> avoid checks on existing channels if the selected institution is not a PSP broker
- PT -> check existing stations only if the selected institution is a creditor institution broker and checks existing channels only if the selected institution is a PSP broker
[PIDM-357](https://pagopa.atlassian.net/browse/PIDM-357)
An institution can change direct/undirect flag on node sign in form only if it has not station and/or channels. Checks on existing stations and/or channels should be made only if the selected institution is already a broker otherwise it cannot have station/channel and so the checks are useless
expected) …
> [PIDM-357] fix: Node sign in checks
